/** 用户相关模块 */
declare namespace Auth {
  /**
   * 用户角色类型(前端静态路由用角色类型进行路由权限的控制)
   * - super: 超级管理员(该权限具有所有路由数据)
   * - admin: 管理员
   * - user: 用户
   */
  type RoleType = 'super' | 'admin' | 'user';
  interface Role {
    id: number;
    name: string;
    smsWarningLevel: number;
    menuIds: number[];
    ioptr: null;
    itime: null;
    uoptr: null | string;
    utime: null | string;
    staffCount: null;
    menuTree: null;
  }
  /** 用户信息 */
  interface UserInfo {
    id: string;
    username: string;
    realName?: string;
    headUrl?: null;
    gender?: number;
    email?: string;
    mobile?: string;
    deptId?: null;
    superAdmin?: number;
    status?: number;
    remark?: null;
    createDate?: string;
    roleIdList?: string[];
    postIdList?: string[];
    deptName?: null;
    labels?: string[];
    confirmPassword?: any;
    password?: any;
  }

  interface LoginPwdModel {
    mobile: string;
    password: string;
    captcha: string;
    uuid: string;
  }
}

// Generated by https://quicktype.io

declare namespace UserManagement {
  interface User extends ApiUserManagement.User {
    /** 序号 */
    index: number;
    /** 表格的key（id） */
    key: string;
  }

  /**
   * 用户性别
   * - 0: 女
   * - 1: 男
   */
  type GenderKey = NonNullable<User['gender']>;

  /**
   * 用户状态
   * - 1: 启用
   * - 2: 禁用
   * - 3: 冻结
   * - 4: 软删除
   */
  type UserStatusKey = NonNullable<User['status']>;
}
